name = "templates_tools"
description = "Test and release tooling for the templates crate"
version = "0.1.0-dev"

authors = ["Bent Bracke"]
maintainers = ["Bent Bracke <bent@example.com>"]
maintainers-logins = ["bbracke"]

licenses = "MIT OR Apache-2.0"
website = ""
tags = ["templates", "tooling", "release", "tests"]

project-files = ["templates_tools.gpr"]

[[depends-on]]
project_tools = "*"

[[depends-on]]
templates = "*"

[[pins]]
project_tools = { path = "../../project_tools" }

[[pins]]
templates = { path = ".." }
